name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Save Google Credentials to file
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/service_account.json
        shell: bash

      - name: Run Python script
        run: python myapp.py

