name: Google Drive Integration

on:
  push:
    branches:
      - main

jobs:
  access-drive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Decode and save the JSON secret as a file
      - name: Set up Google Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          if [ -z "$GOOGLE_APPLICATION_CREDENTIALS_JSON" ]; then
            echo "GOOGLE_APPLICATION_CREDENTIALS_JSON is not set or empty"
            exit 1
          fi
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service_account.json

      # Check if the file was written correctly
      - name: Verify Credentials File
        run: |
          if [ -f service_account.json ]; then
            echo "Credentials file exists."
            cat service_account.json
          else
            echo "Failed to create service_account.json"
            exit 1
          fi

      # Validate JSON structure
      - name: Validate JSON File
        run: |
          python3 -c "import json; json.load(open('service_account.json'))"
          echo "JSON file is valid."

      # Set up Python environment
      - name: Set Up Python Environment
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      # Run the application
      - name: Run Application
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service_account.json
        run: |
          source env/bin/activate
          python3 myapp.py
