name: Google Drive Integration

on:
  push:
    branches:
      - main

jobs:
  access-drive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Google Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service_account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service_account.json" >> $GITHUB_ENV

      - name: Validate Credentials File
        run: |
          python3 -c "import json; json.load(open('service_account.json'))"

      - name: Set Up Python Environment
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Run Script
        run: |
          source env/bin/activate
          python3 myapp.py
