name: Google Drive Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read  # Required to access the repository content
  secrets: read   # Ensure secrets can be accessed

jobs:
  access-drive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Google Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" | base64 --decode > service_account.json

      - name: Check Credentials File
        run: |
          if [ -f service_account.json ]; then
            echo "Credentials file exists."
          else
            echo "Credentials file does not exist."
            exit 1
          fi

      - name: Validate JSON File
        run: |
          python3 -c "import json; json.load(open('service_account.json'))"
      
      - name: Check Environment Variable
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/service_account.json"
      
      - name: Set Up Python Environment
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Run Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service_account.json
        run: |
          source env/bin/activate
          python3 myapp.py
