name: Google Drive Integration

on:
  push:
    branches:
      - main

jobs:
  access-drive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Google Credentials
        run: |
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > service_account.json

      - name: Install Python Dependencies
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Run Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service_account.json
        run: |
          python3 myapp.py
